### ISSUE TITLE
There doesn't seem to be a way to produce an apostrophe keypress

### ISSUE THREAD

**Issue by periata** [codesqueak/Nascom#10]
The Nascom 2 keyboard definitely has an apostrophe (it's accessed with shift+7, based on [this photo](https://nascom.wordpress.com/nascom/hardware/nascom-2-2/n2-keyboard/)), but I don't seem to be able to actually enter one (either that or neither NAS-SYS nor ZEAP allow one to be entered for some reason -- I don't see why that would be the case, but as I have no actual experience using these programs before now I cannot guarantee that they do).

For reference, I'm using a UK keyboard, so my apostrophe key is unshifted and shared with '@' (which does work fine).  I believe the keycode for this in Java is `KeyEvent.VK_QUOTE`.  I think this should be toggling bit 2 of scan line 3, and of course the shift button, which I believe is bit 4 of scan line 0 (but I can't be sure of either of these, because I'm reading somebody else's code, as I can't find a good reference to the keyboard hardware of the Nascom 2).

**Comment by codesqueak** [comment]
The character can be produced by using CTRL-SHIFT-G

However, it shoud be available from the Apostrophe / @ key as well.

**Comment by codesqueak** [comment]
Tweaked kayboard handler to add apostrophe. Also added { and } at the same time.

**Comment by codesqueak** [comment]
Fixed in FIX-Keyboard

**Comment by codesqueak** [comment]
https://github.com/codesqueak/Nascom/pull/13
