### ISSUE TITLE
Cassette input not working when cassette LED turned off

### ISSUE THREAD

**Issue by periata** [codesqueak/Nascom#11]
I'm not sure whether this is entirely correct, but the cassette handling routines seem to have been written so that cassette input is only enabled when the cassette LED is turned on -- however, as far as I can tell without a physical machine to test on there is no such restriction on the actual machine.

The schematics at http://www.nascomhomepage.com/pdf/Nascom2.pdf seem to show that the cassette LED (which I believe is "LED2" in the bottom right hand corner of page 2 of the schematic) is simply a software controlled indicator with no actual influence on the tape reading hardware (which is located on the left hand side of page 2 of the schematic).

This appears to be causing it to be impossible to load saved files into ZEAP, and potentially other applications that rely on processing saved files through the same interface as keyboard input.

**Comment by periata** [comment]
I've uploaded a change that works for me to fix this issue; see pull request linked above.

**Comment by codesqueak** [comment]
Thanks for the fix.  Now merged.  I'll have a look at the other two issues as time permits.
